services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - /var/log/chesley_web:/var/log/chesley_web
      - /opt/website/run:/opt/website/run
    env_file:
      - .env.prod
    user: "1002:33"
    restart: always
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    networks:
      - website_network

networks:
  website_network:
    driver: bridge
