services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    volumes:
      - .:/app
      - sqlite_data:/app/db
      - ./logs:/app/logs
      - /home/critter/projects/Website-files/images-website/input_dir:/app/external_input_dir
      - /home/critter/projects/Website-files/images-website/processed_dir:/app/external_processed_dir
      - /home/critter/projects/Website-files/images-website/original_dir:/app/external_original_dir

volumes:
  sqlite_data:
