webapps@ip-172-31-46-83:/opt/website$ cat docker-compose.prod.yml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - .:/opt/website
      - /opt/website/staticfiles:/opt/website/staticfiles
      - /var/log/chesley_web/django:/var/log/chesley_web/django
      - /var/log/chesley_web/gunicorn:/var/log/chesley_web/gunicorn
      - /etc/ssl/certs/rds:/etc/ssl/certs/rds:ro
      - /opt/website/run:/opt/website/run
    env_file:
      - .env.prod
    environment:
      - DJANGO_SETTINGS_MODULE=chesley_web.settings.production
    user: "1002:33"  # UID of webapps and GID of www-data
    restart: always
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        mkdir -p /opt/website/run &&
        chmod 775 /opt/website/run &&
        gunicorn chesley_web.wsgi:application -c /opt/website/gunicorn.conf.py
      "
