services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - AWS_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
        - AWS_STORAGE_BUCKET_NAME=${R2_STORAGE_BUCKET_NAME}
    volumes:
      - /var/log/chesley_web:/var/log/chesley_web
      - /opt/website/run:/opt/website/run
    env_file:
      - .env.prod
    user: "1002:33"
    restart: always
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    networks:
      - website_network

networks:
  website_network:
    driver: bridge
