FROM python:3.12

ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Install Python dependencies
COPY requirements-dev.txt /app/
RUN pip install --no-cache-dir -r requirements-dev.txt

# Run the development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
