name: Deploy to EC2 using AWS Systems Manager

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup SSH key
        env:
          DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY_GITHUB }}
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/github_actions_deploy
          chmod 600 ~/.ssh/github_actions_deploy
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Deploy to EC2 using AWS Systems Manager
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --parameters '{
              "commands": [
                "LOG_FILE=/var/log/chesley_web/deployment.log",
                "mkdir -p /var/log/chesley_web",
                "touch $LOG_FILE",
                "chmod 644 $LOG_FILE",
                "echo \"Deployment started at $(date)\" >> $LOG_FILE",
                "cd /opt/website",
                "echo \"Current directory: $(pwd)\" >> $LOG_FILE",
                "echo \"Git configuration:\" >> $LOG_FILE",
                "sudo -u webapps git config --list >> $LOG_FILE",
                "echo \"Before git operations:\" >> $LOG_FILE",
                "sudo -u webapps git status >> $LOG_FILE",
                "sudo -u webapps git rev-parse HEAD >> $LOG_FILE",
                "echo \"Fetching changes:\" >> $LOG_FILE",
                "sudo -u webapps GIT_SSH_COMMAND=\"ssh -i ~/.ssh/github_actions_deploy -o IdentitiesOnly=yes\" git fetch --all >> $LOG_FILE 2>&1 || { echo \"Git fetch failed\" >> $LOG_FILE; exit 1; }",
                "echo \"Resetting to origin/main:\" >> $LOG_FILE",
                "sudo -u webapps GIT_SSH_COMMAND=\"ssh -i ~/.ssh/github_actions_deploy -o IdentitiesOnly=yes\" git reset --hard origin/main >> $LOG_FILE 2>&1 || { echo \"Git reset failed\" >> $LOG_FILE; exit 1; }",
                "echo \"After git operations:\" >> $LOG_FILE",
                "sudo -u webapps git status >> $LOG_FILE",
                "sudo -u webapps git rev-parse HEAD >> $LOG_FILE",
                # ... rest of your deployment commands ...
              ]
            }' \
            --output text
