name: Prepare for Deployment

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

jobs:
  prepare-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: Prepare for deployment
      run: |
        # Add steps to prepare for deployment
        # This might involve creating a deployment package or updating a manifest
        echo "Preparing for deployment..."
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false
