name: Prepare for Deployment

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

jobs:
  prepare-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Download Docker image artifact
      uses: actions/download-artifact@v4
      with:
        name: docker-image
        run-id: ${{ github.event.workflow_run.id }}
    - name: Load Docker image
      run: docker load < image.tar
    - name: Prepare for deployment
      run: |
        # Add steps to prepare for deployment
        echo "Preparing for deployment..."
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false
