name: Sync Images to S3

on:
  push:
    paths:
      - 'static/images/**'

jobs:
  sync-to-s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Sync images to S3
        run: |
          # Sync with cache control headers
          aws s3 sync ./static/images s3://${{ secrets.AWS_S3_BUCKET_NAME }}/static/images \
            --delete \
            --exclude "*" \
            --include "*.jpg" \
            --include "*.jpeg" \
            --include "*.png" \
            --include "*.gif" \
            --include "*.webp" \
            --include "*.svg" \
            --cache-control "public,max-age=31536000,immutable" \
            --metadata-directive REPLACE

          # Verify sync and cache settings
          echo "Verifying sync and cache settings..."
          aws s3api list-objects-v2 \
            --bucket ${{ secrets.AWS_S3_BUCKET_NAME }} \
            --prefix static/images \
            --query 'Contents[].{Key: Key, CacheControl: CacheControl}' \
            --output table
