name: Sync Images to S3

on:
  push:
    paths:
      - 'static/images/**'
      - 'media/**'

jobs:
  sync-to-s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Sync images to S3
        run: |
          aws s3 sync ./static/images s3://${{ secrets.AWS_S3_BUCKET_NAME }}/static/images --delete
          aws s3 sync ./media s3://${{ secrets.AWS_S3_BUCKET_NAME }}/media --delete
