name: Test and Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install flake8

    - name: Run tests
      env:
        DEV_SECRET_KEY: ${{ secrets.DEV_SECRET_KEY }}
        DEV_DB_NAME: ${{ secrets.DEV_DB_NAME }}
        DEV_DB_USER: ${{ secrets.DEV_DB_USER }}
        DEV_DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
      run: python manage.py test

    - name: Run linter
      run: flake8 .

  build-docker:
    needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.prod  # Specify the Dockerfile.prod
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/chesley-web:${{ github.sha }}
