name: Test and Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    env:
      DEV_SECRET_KEY: ${{ secrets.DEV_SECRET_KEY }}
      DEV_DB_NAME: ${{ secrets.DEV_DB_NAME }}
      DEV_DB_USER: ${{ secrets.DEV_DB_USER }}
      DEV_DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
      DJANGO_SETTINGS_MODULE: chesley_web.settings.ci
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install flake8
      - name: Run tests
        run: python manage.py test
      - name: Run linter
        run: flake8 .
